import "./globals.css";

import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";

import Navbar from "@/components/ui/Navbar/Navbar";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-roboto-condensed",
  display: "swap",
});

export const metadata: Metadata = {
  title: "3d social media ",
  description: "Generated by JAsmeet",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoCondensed.variable} antialiased`}>
      <body className="min-h-screen w-full bg-background">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
